services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED:-true}
      KC_HOSTNAME: ${KC_HOSTNAME-localhost}
      KC_IMPORT: ${KC_IMPORT:-/opt/keycloak/data/import/realm-export.json}
      KC_HTTP_PORT: ${KC_HTTP_PORT:-8080}
      KC_HTTPS_PORT: ${KC_HTTP_PORT:-8443}
    ports:
      - ${EXPOSED_KC_HTTP_PORT:-8080}:${KC_HTTP_PORT:-8080}
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
