FROM ghcr.io/graalvm/graalvm-community:21 AS build
ARG GITLAB_MAVEN_REGISTRY_URL
ARG HOME
WORKDIR /app
COPY . /app
RUN --mount=type=bind,source=.m2,target=/root/.m2 \
    ./gradlew clean nativeCompile

# Final image
FROM ubuntu:22.04
WORKDIR /app
COPY --from=build /app/cf-application/build/native/nativeCompile/* /opt/
EXPOSE 8080
ENTRYPOINT ["/opt/cf-application"]
