server:
  port: 9000

spring:
  docker:
    compose:
      lifecycle-management: start-and-stop

  threads:
    virtual:
      enabled: true

  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUD
    open-in-view: false

  sql:
    init:
      mode: never
      #schema-locations: classpath:db/schema.sql

  datasource:
    name: ${DB_NAME:lob_service}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=lob_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

    hikari:
      minimum-idle: ${DB_MIN_IDLE:2}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      schema: ${DB_SCHEMA:lob_service}

    jpa:
      database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
      hibernate:
        ddl-auto: none
        show_sql: ${JPA_SHOW_SQL:false}

  flyway:
      locations: classpath:db/migration/{vendor}
      out-of-order: true
      url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
      user: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
      schemas: ${DB_SCHEMA:lob_service}
      # baselineOnMigrate this will create a baseline version if none exists (https://flywaydb.org/documentation/configuration/parameters/baselineOnMigrate)
      baselineOnMigrate: true
      enabled: true
      validateMigrationNaming: true

  web:
    resources:
      add-mappings: false
    # disable static content handling
    spring.web.resources.add-mappings: false
    spring.mvc.throw-exception-if-no-handler-found: true
    # force charset in request and responses
    servlet:
      encoding:
        force: true

    exposure:
      include: ${WEB_EXPOSURE_INCLUDE:health,info,prometheus,metrics,flyway,applicationmodules}

  artemis:
    embedded:
      topics=target: target

  main:
    allow-bean-definition-overriding: true

  health:
    enabled: ${HEALTH_ENABLED:true}

  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_SHOW_DETAILS:always}

  modulith:
    events:
      externalization:
        enabled: true

    jdbc:
      schema-initialization:
        enabled: true

    republish-outstanding-events-on-restart: true

lob:
  netsuite:
    client:
      realm: 6766746_SB1
      oauth_nonce: NN9H7V6319V
      consumer_key: 23498aa75f9a87ffc50eb78c42b4cc413974500d1e01307d950ae83b85460e53
      token_secret: 4b7c015da837267bfe205a316b7357b0e18fc5dccf4a8b06c46554a155ead4d2
      consumer_secret: 330100b0a2be6dc76f50ba7f3c7077a9d00f4a4685dfd64e862b389b960b7ff6
      token: 1496b695d6cb266b1505b363a549b1db3a0566ed28459d03d7c013fdad0669a4
      url: https://6766746-sb1.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=384&deploy=1&searchname=transaction_search_cm

  l1:
    transaction:
      metadata:
        label: "22222"
