export enum TransactionPendingInvalidStatus {
    VAT_DATA_NOT_FOUND = "VAT_DATA_NOT_FOUND",
    COST_CENTER_DATA_NOT_FOUND = "COST_CENTER_DATA_NOT_FOUND",
    CHART_OF_ACCOUNT_NOT_FOUND = "CHART_OF_ACCOUNT_NOT_FOUND",
    UNBALANCED_TRANSACTION = "UNBALANCED_TRANSACTION",
    FCY_BALANCE_MUST_BE_ZERO = "FCY_BALANCE_MUST_BE_ZERO",
    LCY_BALANCE_MUST_BE_ZERO = "LCY_BALANCE_MUST_BE_ZERO",
    TX_INTERNAL_NUMBER_MUST_BE_PRESENT = "TX_INTERNAL_NUMBER_MUST_BE_PRESENT",
    ACCOUNT_CODE_DEBIT_IS_EMPTY = "ACCOUNT_CODE_DEBIT_IS_EMPTY"
}