package org.cardanofoundation.lob.app.accounting_reporting_core.domain.core;

import org.cardanofoundation.lob.app.organisation.domain.core.OrganisationCurrency;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Optional;

public record TransactionLine(

        // mandatory values

        String id, // unique identifier for a transaction line, generated by us global currencyId

        String organisationId, // unique identifier for an organisation, generated by LOB

        TransactionType transactionType, // LOB transaction type

        LocalDateTime entryDate, // date of the transaction

        String transactionNumber, // unique transaction number, organisation level value

        String accountCodeDebit, //

        // base currency specific value to the organisation
        CurrencyPair baseCurrency,

        // target to which we convert
        CurrencyPair targetCurrency,

        BigDecimal fxRate,

        /// optionals below

        Optional<String> documentNumber,

        Optional<String> vendorCode,

        Optional<String> vendorName,

        Optional<String> costCenter,

        Optional<String> projectCode,

        Optional<VatPair> vat,

        Optional<String> accountNameDebit,

        Optional<String> accountCredit,

        Optional<String> memo,

        Optional<BigDecimal> amountFcy,

        Optional<BigDecimal> amountLcy) {

    public record CurrencyPair(OrganisationCurrency organisationCurrency, Currency currency) {
    }

    public record VatPair(String vatCode, BigDecimal vatRate) {
    }

}

