version: "3.9"

services:

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      #ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
      ALLOW_UNSIGNED: true
    ports:
      - 2181:2181
    networks:
      - public_net
  kafka:
    build: docker/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - 29092:29092
      - 8085:8085
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_PORT: 9997
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SCHEMA_REGISTRY_URL: "kafka:8085"
    networks:
      - public_net
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  kafka-ui:
    container_name: kafka-ui
    hostname: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    volumes:
      - ./docker/kafka-ui/config.yml:/config.yml
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      SPRING_CONFIG_ADDITIONAL-LOCATION: /config.yml

    networks:
      - public_net

  maven:
    build: docker/maven
    container_name: maven
    ports:
      - 8081:8080
    #working_dir: /usr/src/mymaven
    volumes:
      - ./:/app
    networks:
      - public_net

volumes:
  kafka_data:
    driver: local
networks:
  public_net:
    name: api_public_net
    driver: bridge
