# here we specify only properties to override from the default values specified in the application.properties file

# local YaciDevKit network, see: https://github.com/bloxbean/yaci-devkit

spring:
  env:
    active: dev--yaci-dev-kit

  flyway:
    out-of-order: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMA:lob_service}
    # baselineOnMigrate this will create a baseline version if none exists (https://flywaydb.org/documentation/configuration/parameters/baselineOnMigrate)
    baselineOnMigrate: true
    enabled: true
    validateMigrationNaming: true
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/migration/{vendor}/common
      - classpath:db/migration/{vendor}/dev

lob:
  cardano:
    network: ${LOB_CARDANO_NETWORK:DEV}

  blockchain_publisher:
    dispatcher:
      enabled: ${LOB_BLOCKCHAIN_PUBLISHER_ENABLED:true}
    watchdog:
      enabled: ${LOB_BLOCKCHAIN_WATCHDOG_ENABLED:true}
      fixed_delay: ${LOB_BLOCKCHAIN_WATCHDOG_FIXED_DELAY:PT1M}
      initial_delay: ${LOB_BLOCKCHAIN_WATCHDOG_INITIAL_DELAY:PT1M}

  dispatching_strategy:
    type: ${LOB_DISPATCHING_STRATEGY_TYPE:IMMEDIATE}

  blockfrost:
    url: "http://localhost:8080/api/v1/"
  # locally YaciDevKit runs on port 8080
    api_key: ""

  # it is implicit here because on sandbox we have problems accessing explicit accounting period
  netsuite_financial_period_source: IMPLICIT

l1:
  transaction:
    debug_store_output_tx: ${LOB_L1_TRANSACTION_DEBUG_STORE_OUTPUT_TX:false}
    metadata_validation:
      enable: ${LOB_L1_TRANSACTION_METADATA_VALIDATION_ENABLE:true}

# yaci-store properties
  cardano:
    host: ${LOB_STORE_HOST:localhost}
    port: ${LOB_STORE_PORT:3001}
    # 42 is protocol magic for Yaci-Dev-Kit
    protocol-magic: 42
    # for devnet we must specify the genesis files for Yaci-Store
    byron-genesis-file: classpath:/devel/config/devkit/byron-genesis.json
    shelley-genesis-file: classpath:/devel/config/devkit/shelley-genesis.json
    alonzo-genesis-file: classpath:/devel/config/devkit/alonzo-genesis.json
    conway-genesis-file: classpath:/devel/config/devkit/conway-genesis.json

  sync-start-blockhash:
  sync-start-slot: 0
