spring:
  env:
    active: prod
  flyway:
    locations:
      - classpath:db/migration/{vendor}/common # common is needed to load the scripts from cf-reeve-platform
      - classpath:db/migration/{vendor}/cf-reeve-db-migrations/common # custom common migrations for CF, use test migrations as an example
      - classpath:db/migration/{vendor}/cf-reeve-db-migrations/prod # custom prod migrations for CF, use test migrations as an example
