name: Run Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test
        run: |
         ./gradlew clean build

#  mutation-test:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup JDK 18
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'corretto'
#          cache: maven
#
#      - name: Build
#        run: |
#          mvn --batch-mode --update-snapshots clean package -DskipTests
#
##      - name: Test
##        run: |
##          mvn test-compile org.pitest:pitest-maven:mutationCoverage -DmutationThreshold=39
#
##      - name: Publish mutation test report to GitHub Pages
##        uses: JamesIves/github-pages-deploy-action@v4
##        if: github.ref == 'refs/heads/main'
##        with:
##          BRANCH: gh-pages
##          folder: target/pit-reports/
##          target-folder: mutation-report/