name: Run Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use 'zulu', 'adopt', 'oracle', etc., if preferred
          java-version: '21'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout platform code
        uses: actions/checkout@v3
        with:
          repository: cardano-foundation/cf-lob-platform
          ref: refs/heads/main
          path: platform
      - name: Build platform
        run: |
          cd platform
          ./gradlew clean build publishMavenJavaPublicationToLocalM2Repository -x test
      - name: Run tests
        run: |
          ./gradlew test

  mutation-test:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/
