name: Run Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build files & copy files
        run: |
          docker build --target build -t cf-lob .
      - name: Start container and copy files
        run: |
          # Start a container from the cf-lob image
          docker run --name cf-lob-container -d cf-lob tail -f /dev/null
          
          # Copy files from the container to the host
          docker cp cf-lob-container:/app ./app
          
          # Remove the container
          docker rm -f cf-lob-container
      - name: Run test
        run: cd ./app && ./gradlew test