name: Postman Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services..."
          sleep 90 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman Collection with Environment
        run: |
          newman run postman/Reeve_Integration.postman_collection.json \
            --environment postman/Reeve_env.postman_environment.json