name: Postman Tests

on:
  pull_request:
env:
  REEVE_DB_MIGRATIONS_REPO: cardano-foundation/cf-reeve-db-migrations
  REEVE_DB_MIGRATIONS_REF: main
  REEVE_DB_MIGRATIONS_PATH: cf-application/src/main/resources/db/migration/postgresql/cf-reeve-db-migrations

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout cf-reeve-db-migrations
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REEVE_DB_MIGRATIONS_REPO }}
          ref: ${{ env.REEVE_DB_MIGRATIONS_REF }}
          ssh-key: ${{ secrets.CF_REEVE_DB_MIGRATIONS_SSH_DEPLOY_KEY }}
          path: ${{ env.REEVE_DB_MIGRATIONS_PATH }}

      - name: Set up Docker Compose
        run: |
          docker compose up -d --build
          timeout 150 docker compose logs -f api || true
      - name: Services health-check API
        run: |
          timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9000/swagger-ui/index.html)" != "200" ]]; do sleep 2;echo "."; done'
          echo "API is up"
          docker ps
      - name: Services health-check Keycloak
        run: |
          timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/realms/master)" != "200" ]]; do sleep 2;echo "."; done'
          echo "Keycloak is up"
          docker ps

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman (Postman CLI)
        run: npm install -g newman
      - name: Run Postman Collection with Environment
        run: |
          newman run postman/Reeve_Integration.postman_collection.json \
            --environment postman/Reeve_env.postman_environment.json
            --timeout 5000