name: e2e Tests

on:
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  REEVE_DB_MIGRATIONS_REPO: cardano-foundation/cf-reeve-db-migrations
  REEVE_DB_MIGRATIONS_REF: main
  REEVE_DB_MIGRATIONS_PATH: cf-application/src/main/resources/db/migration/postgresql/cf-reeve-db-migrations
  GITLAB_MAVEN_REGISTRY_URL: ${{ secrets.GITLAB_MAVEN_REGISTRY_URL }}

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout cf-reeve-db-migrations
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REEVE_DB_MIGRATIONS_REPO }}
          ref: ${{ env.REEVE_DB_MIGRATIONS_REF }}
          ssh-key: ${{ secrets.CF_REEVE_DB_MIGRATIONS_SSH_DEPLOY_KEY }}
          path: ${{ env.REEVE_DB_MIGRATIONS_PATH }}

      - name: Set up Docker Compose
        run: |
          docker compose build --build-arg GITLAB_MAVEN_REGISTRY_URL="${GITLAB_MAVEN_REGISTRY_URL}"
          docker compose up -d --wait --quiet-pull

          # debugging
          docker compose logs api --tail 500
          docker ps

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman (Postman CLI)
        run: npm install -g newman
      - name: Run Postman Collection with Environment
        run: |
          newman run postman/Reeve_Integration.postman_collection.json \
            --environment postman/Reeve_env.postman_environment.json

      - name: Clean up Docker
        if: always()
        run: docker compose down -v

  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout cf-reeve-db-migrations
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REEVE_DB_MIGRATIONS_REPO }}
          ref: ${{ env.REEVE_DB_MIGRATIONS_REF }}
          ssh-key: ${{ secrets.CF_REEVE_DB_MIGRATIONS_SSH_DEPLOY_KEY }}
          path: ${{ env.REEVE_DB_MIGRATIONS_PATH }}

      - name: Set up Docker Compose
        run: |
          docker compose build --build-arg GITLAB_MAVEN_REGISTRY_URL="${GITLAB_MAVEN_REGISTRY_URL}"
          docker compose up -d --wait --quiet-pull

          # debugging
          docker compose logs api --tail 500
          docker ps

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Playwright dependencies
        working-directory: playwright
        run: |
          npm ci 
          npx playwright install --with-deps
          npm install -g allure-commandline

      - name: Create .env file
        working-directory: playwright
        run: |
          echo "API_URL=http://localhost:9000/api/v1" >> .env
          echo "LOGIN_URL=http://localhost:8080" >> .env
          echo "MANAGER_USER=${{ secrets.PLAYWRIGHT_USER }}" >> .env
          echo "MANAGER_PASSWORD=${{ secrets.PLAYWRIGHT_PASSWORD }}" >> .env
          echo "API_LOG_REQUEST=false" >> .env
          echo "ORGANIZATION_ID=${{ secrets.PLAYWRIGHT_ORGANIZATION_ID }}" >> .env
          echo "CI=true" >> .env

      - name: Run Playwright e2e tests
        working-directory: playwright
        run: npm run test
        continue-on-error: true

      - name: Load Test Report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Test Report history
        if: always()
        continue-on-error: true
        run: |
          mkdir -p playwright/allure-results/history
          cp -r gh-pages/allure-report/history/* playwright/allure-results/history/ 2>/dev/null || true

      - name: Generate New Test Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate playwright/allure-results --clean -o allure-report

      - name: Deploy Test Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: allure-report
          keep_files: true

      - name: Clean up Docker
        if: always()
        run: docker compose down -v
